workloads:
        - graph: '/opt/dask-distributed/benchmark/881fe99a.g'
          execution: '/opt/dask-distributed/benchmark/881fe99a.json'
topology:
   w1:
      executors: 3
      type: worker
      name: w1
      memory: 32000000 
      cache.policy: FIFO 
      cache.port: 9001 
      ip: 192.168.1.2
      storage: 192.168.3.2:9000
      rate: 10737418240
      gateway: r1 
   w2:
      executors: 3
      type: worker
      name: w2
      memory: 32000000 # 32MB  
      cache.policy: FIFO 
      cache.port: 9001 
      ip: 192.168.1.3
      storage: 192.168.3.2:9000
      rate: 10737418240
      gateway: r1 
   r1:
      type: router
      name: r1
      ports: 6
      rate: 10737418240
      ip: 192.168.1.1
      gateway: r3 
   w3:
      executors: 3
      type: worker
      name: w3
      rate: 10737418240
      memory: 32000000 # 32MB  
      cache.policy: FIFO 
      cache.port: 9001 
      ip: 192.168.1.4
      gateway: r1 
      storage: 192.168.3.2:9000
   w4:
      executors: 3
      type: worker
      name: w4
      rate: 10737418240
      memory: 32000000 # 32MB  
      cache.policy: FIFO 
      cache.port: 9001 
      ip: 192.168.1.5
      gateway: r1
      storage: 192.168.3.2:9000
   r2:
      type: router
      name: r2
      ports: 4
      rate: 10737418240
      ip: 192.168.2.1
      gateway: r3 
   r3:
      type: router
      name: r3
      rate: 10737418240
      ports: 4
      ip: 192.168.3.1
      gateway: None 
   s1:
      type: storage
      name: s1
      ip: 192.168.3.2
      port: 9000
      rate: 10737418240
      storage_rate: 104857600 #100MBps
      metadata: /local0/wlmod/simulator/karizsim/inputs.csv
      gateway: r3
