benchmark:
  log: /local0/serverless/serverless-sim/results/tree_reduction_dag.syncwdeser.chain_color.log
  workloads:
  - execution: ./stats/tree_reduction_dag.json   #/opt/dask-distributed/benchmark/stats/tree_reduction_1024B_0131e41b.json
    graph: ./stats/tree_reduction_dag.g #/opt/dask-distributed/benchmark/stats/tree_reduction_1024B_0131e41b.g
cluster:
  scheduling: chain_color
  serialization: syncwdeser
  prefetch: 0
topology:
  r1:
    gateway: r3
    ip: 192.168.1.1
    name: r1
    ports: 32
    rate: 2684354560
    type: router
  r2:
    gateway: r3
    ip: 192.168.2.1
    name: r2
    ports: 4
    rate: 2684354560
    type: router
  r3:
    gateway: None
    ip: 192.168.3.1
    name: r3
    ports: 4
    rate: 2684354560
    type: router
  s1:
    gateway: r3
    ip: 192.168.3.2
    metadata: /local0/wlmod/simulator/karizsim/inputs.csv
    name: s1
    port: 9000
    rate: 2684354560
    storage_rate: 104857600
    type: storage
  w1:
    cache.policy: FIFO
    cache.port: 9001
    executors: 1
    gateway: r1
    ip: 192.168.1.10
    memory: 322000000
    name: w1
    rate: 2684354560
    storage: 192.168.3.2:9000
    type: worker
  w2:
    cache.policy: FIFO
    cache.port: 9001
    executors: 1
    gateway: r1
    ip: 192.168.1.203
    memory: 322000000
    name: w2
    rate: 2684354560
    storage: 192.168.3.2:9000
    type: worker
  w3:
    cache.policy: FIFO
    cache.port: 9001
    executors: 1
    gateway: r1
    ip: 192.168.1.44
    memory: 322000000
    name: w3
    rate: 2684354560
    storage: 192.168.3.2:9000
    type: worker
  w4:
    cache.policy: FIFO
    cache.port: 9001
    executors: 1
    gateway: r1
    ip: 192.168.1.165
    memory: 322000000
    name: w4
    rate: 2684354560
    storage: 192.168.3.2:9000
    type: worker
