benchmark:
  log: /local0/serverless-sim/results/c1186f35_837e.syncnodeser.chain_color.log
  workloads:
  - execution: /opt/dask-distributed/benchmark/stats/c1186f35_837e.json
    graph: /opt/dask-distributed/benchmark/stats/c1186f35_837e.g
cluster:
  scheduling: chain_color
  serialization: syncnodeser
topology:
  r1:
    gateway: r3
    ip: 192.168.1.1
    name: r1
    ports: 32
    rate: 2684354560
    type: router
  r2:
    gateway: r3
    ip: 192.168.2.1
    name: r2
    ports: 4
    rate: 2684354560
    type: router
  r3:
    gateway: None
    ip: 192.168.3.1
    name: r3
    ports: 4
    rate: 2684354560
    type: router
  s1:
    gateway: r3
    ip: 192.168.3.2
    metadata: /local0/wlmod/simulator/karizsim/inputs.csv
    name: s1
    port: 9000
    rate: 2684354560
    storage_rate: 104857600
    type: storage
  w1:
    cache.policy: FIFO
    cache.port: 9001
    executors: 32
    gateway: r1
    ip: 192.168.1.2
    memory: 322000000
    name: w1
    rate: 2684354560
    storage: 192.168.3.2:9000
    type: worker
  w2:
    cache.policy: FIFO
    cache.port: 9001
    executors: 32
    gateway: r1
    ip: 192.168.1.3
    memory: 322000000
    name: w2
    rate: 2684354560
    storage: 192.168.3.2:9000
    type: worker
  w3:
    cache.policy: FIFO
    cache.port: 9001
    executors: 32
    gateway: r1
    ip: 192.168.1.4
    memory: 322000000
    name: w3
    rate: 2684354560
    storage: 192.168.3.2:9000
    type: worker
  w4:
    cache.policy: FIFO
    cache.port: 9001
    executors: 32
    gateway: r1
    ip: 192.168.1.5
    memory: 322000000
    name: w4
    rate: 2684354560
    storage: 192.168.3.2:9000
    type: worker
