benchmark:
  logdir: /local0/serverless/serverless-sim/results/
  statistics: /local0/serverless/serverless-sim/results/statistics.csv
  workloaddir: /opt/dask-distributed/benchmark/stats/
  workloads:
  - randomnearest5x41GB1B_d41204ff
cluster:
  prefetch: 0
  scheduling: chain_color_rr
  serialization: syncwdeser
topology:
  r1:
    gateway: r3
    ip: 10.255.23.1
    name: r1
    ports: 32
    rate: 2684354560
    type: router
  r2:
    gateway: r3
    ip: 10.255.24.1
    name: r2
    ports: 4
    rate: 2684354560
    type: router
  r3:
    gateway: None
    ip: 10.255.22.1
    name: r3
    ports: 4
    rate: 2684354560
    type: router
  s1:
    gateway: r3
    ip: 10.255.22.2
    metadata: /local0/wlmod/simulator/karizsim/inputs.csv
    name: s1
    port: 9000
    rate: 2684354560
    storage_rate: 104857600
    type: storage
  w1:
    cache.policy: FIFO
    cache.port: 9001
    executors: 1
    gateway: r1
    ip: 10.255.23.108
    memory: 322000000
    name: w1
    rate: 2684354560
    storage: 10.255.22.2:9000
    type: worker
  w2:
    cache.policy: FIFO
    cache.port: 9001
    executors: 1
    gateway: r1
    ip: 10.255.23.109
    memory: 322000000
    name: w2
    rate: 2684354560
    storage: 10.255.22.2:9000
    type: worker
  w3:
    cache.policy: FIFO
    cache.port: 9001
    executors: 1
    gateway: r1
    ip: 10.255.23.110
    memory: 322000000
    name: w3
    rate: 2684354560
    storage: 10.255.22.2:9000
    type: worker
  w4:
    cache.policy: FIFO
    cache.port: 9001
    executors: 1
    gateway: r1
    ip: 10.255.23.115
    memory: 322000000
    name: w4
    rate: 2684354560
    storage: 10.255.22.2:9000
    type: worker
