scheduler:
        policy: round_robin # The policy could be round robin, random, consistent hash, Rodrigo's coloring, Mania's coloring
workloads:
        - graph: '/opt/dask-distributed/benchmark/fb405a30.g'
          execution: '/opt/dask-distributed/benchmark/fb405a30.json'
topology:
   w1:
      executors: 3
      type: worker
      name: w1
      memory: 32000000 
      cache.policy: FIFO 
      cache.port: 9001 
      ip: 192.168.1.2
      storage: 192.168.3.2:9000
      rate: 1073741824
      gateway: r1 
   w2:
      executors: 3
      type: worker
      name: w2
      memory: 32000000 # 32MB  
      cache.policy: FIFO 
      cache.port: 9001 
      ip: 192.168.1.3
      storage: 192.168.3.2:9000
      rate: 1073741824
      gateway: r1 
   w6:
      executors: 3
      type: worker
      name: w6
      rate: 1073741824
      memory: 32000000 # 32MB  
      cache.policy: FIFO 
      cache.port: 9001 
      ip: 192.168.1.4
      gateway: r1
      storage: 192.168.3.2:9000
   r1:
      executors: 3
      type: router
      name: r1
      ports: 4
      rate: 1073741824
      ip: 192.168.1.1
      gateway: r3 
   w3:
      executors: 3
      type: worker
      name: w3
      rate: 1073741824
      memory: 32000000 # 32MB  
      cache.policy: FIFO 
      cache.port: 9001 
      ip: 192.168.2.2
      gateway: r2 
      storage: 192.168.3.2:9000
   w4:
      executors: 3
      type: worker
      name: w4
      rate: 1073741824
      memory: 32000000 # 32MB  
      cache.policy: FIFO 
      cache.port: 9001 
      ip: 192.168.2.3
      gateway: r2
      storage: 192.168.3.2:9000
   w5:
      executors: 3
      type: worker
      name: w5
      rate: 1073741824
      memory: 32000000 # 32MB  
      cache.policy: FIFO 
      cache.port: 9001 
      ip: 192.168.2.4
      gateway: r2
      storage: 192.168.3.2:9000
   r2:
      executors: 3
      type: router
      name: r2
      ports: 4
      rate: 1073741824
      ip: 192.168.2.1
      gateway: r3 
   r3:
      executors: 3
      type: router
      name: r3
      rate: 1073741824
      ports: 4
      ip: 192.168.3.1
      gateway: None 
   s1:
      type: storage
      name: s1
      ip: 192.168.3.2
      port: 9000
      rate: 1073741824
      storage_rate: 104857600 #100MBps
      metadata: /local0/wlmod/simulator/karizsim/inputs.csv
      gateway: r3
