benchmark:
  logdir: /local0/serverless/serverless-sim/results/
  statistics: /local0/serverless/serverless-sim/results/statistics.csv
  workloaddir: /opt/dask-distributed/benchmark/stats/
  workloads:
     - all2all4x41GB1B_58e5586a
     - all2all3x41GB1B_fec067dc
cluster:
   configs: /local0/serverless/serverless-sim/configs/config.4n1c.yaml
   policy:
      serialization:
        - syncwdeser 
      scheduling:
        - optimal
        - vanilla
        - random 
        - chain_color_ch
        - round_robin
        - chain_color_rr
