benchmark:
  logdir: /local0/serverless/serverless-sim/results/
  workloaddir: /opt/dask-distributed/benchmark/stats/
  workloads:
     - 0d525495_bca8
cluster:
   configs: /local0/serverless/serverless-sim/configs/config.4n1c.yaml
   policy:
      serialization:
        - syncwdeser 
      scheduling:
        - optimal
        - vanilla
        - random 
        - chain_color_ch
        - round_robin
        - chain_color_rr
